name: build

on: [push]

env:
  sfall_version: 4.3.4
  mpack_version: 4.3.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          set -xeu -o pipefail
          ./extra/tests.sh

      - name: Install packages
        # The Github's Ubuntu images since 20211122.1 are broken
        # https://github.com/actions/virtual-environments/issues/4589
        run: |
          set -xeu -o pipefail
          sudo dpkg --add-architecture i386
          sudo apt -qq update
          sudo apt install -y --allow-downgrades libpcre2-8-0=10.34-7
          sudo apt-get install -o=Dpkg::Use-Pty=0 -y crudini dos2unix gcc p7zip wine-stable wine32
          wineboot

      - name: Build and package
        run: ./extra/full.sh

      - name: Upload artifacts - exe
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: rpu.exe
          path: rpu*.exe

      - name: Upload artifacts - translations zip
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: rpu_translations.zip
          path: rpu*_translations.zip

      # so that main glob doesn't catch it
      - name: Remove translations zip
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: rm -f rpu*_translations.zip

      - name: Upload artifacts - main zip
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: rpu.zip
          path: rpu*.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rpu*.zip
            rpu*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
